add components
ViacheslavKechkin/mini-project-class-components pull request #1
Opened 2022-06-07 14:15 UTC by ViacheslavKechkin

2022-06-10 12:09 UTC, d-vorobyov requested changes

2022-06-10 12:09 UTC, d-vorobyov commented on src/components/Product/index.jsx
> +import plus from "../../assets/icon/plus.svg";
it 's better to avoid many leading dots/slashes, pls make it possible to import like this `"assets/icon/plus.svg"`

2022-06-10 12:09 UTC, d-vorobyov commented on public/index.html
> +    <title>React App</title>
name it somehow another way

2022-06-10 12:09 UTC, d-vorobyov commented on public/index.html
> +    <!--
that's garbage

2022-06-10 12:09 UTC, d-vorobyov commented on public/index.html
> +    <!--
comments I mean, we don't need them I guess

2022-06-10 12:09 UTC, d-vorobyov commented on public/index.html
> +      content="Web site created using create-react-app"
Or maybe "Project I made to figure out class components"

2022-06-10 12:09 UTC, d-vorobyov commented on README.md
> +This section has moved here: [https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify](https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-
too much template information

2022-06-10 12:10 UTC, d-vorobyov commented
Please change PR title/description to more informative

2022-06-10 14:38 UTC, ViacheslavKechkin commented on src/App.jsx
> +        count: count - 1,
I'm doing a destruction and I can't use increment/decrement. Or do I understand something wrong?

2022-06-10 15:21 UTC, ViacheslavKechkin commented on src/components/Products/index.jsx
> +                  <div key={`id-${id}`}>
I have error - Each child in a list should have a unique "key" prop.

2022-06-10 15:27 UTC, ViacheslavKechkin commented on src/components/DeleteProduct/index.jsx
> +      <Button onClick={() => openDeleteWindow(false)} className="button">
Autosave puts this button in one line, apparently because the line length is not very large. Does this need to be fixed?

2022-06-14 08:02 UTC, ViacheslavKechkin commented on src/App.jsx
> +          titleFind={this.state.titleFind}
I decided not to connect it because the project is too small. should I connect it?

2022-06-14 08:14 UTC, d-vorobyov commented on src/components/Products/index.jsx
> +                  <div key={`id-${id}`}>
Yea, since now your list item is `Product` component, pass `key` prop directly to him

2022-06-14 08:53 UTC, d-vorobyov commented on src/App.jsx
> +          titleFind={this.state.titleFind}
It could be quite smaller and cleaner (as much as possible in class components) without so much props :) 
You might also have thought pass something like `parent={this}` to use all parent methods, but remember that parent component always === itself, so it might cause re-render problems, it's anti-pattern.

2022-06-14 08:54 UTC, d-vorobyov commented on src/components/DeleteProduct/index.jsx
> +      <Button onClick={() => openDeleteWindow(false)} className="button">
Ok, let's leave it as linter wants

2022-06-14 09:08 UTC, ViacheslavKechkin commented on src/components/Product/index.jsx
> +            src={plus}
В тз было написано как ниже написал, я сделал похожую логику получается. Как мне сделать что бы было правильнее?
При первом клике товар выбирается в количестве 1 добавляется в "корзину" пользователя.
Происходит пересчет суммы.
Далее пользователь управляет нужным количеством товара в корзине.
При повторном нажатии на карточку, товар убирается из "корзины".

2022-06-14 09:16 UTC, ViacheslavKechkin commented on src/components/Products/index.jsx
> +                    <div key={`id-${id}`}>
I have error - Each child in a list should have a unique "key" prop.

2022-06-14 10:09 UTC, d-lazarev requested changes

2022-06-14 11:24 UTC, d-vorobyov commented on src/components/Product/index.jsx
> +            src={plus}
Seems it was intended in requirements, ok. In that case the whole card should be clickable, now I can't add item to card by click on "plus" button (the whole card controls is inactive) while item count is 0

2022-06-14 12:32 UTC, ViacheslavKechkin commented on src/components/Search/index.jsx
> +            Общая стоимость выбранных блюд: {sum} р.
I didn't quite understand what it was about))

2022-06-14 13:04 UTC, ViacheslavKechkin commented on src/App.jsx
> +    this.productList = [...this.state.products];
previously used and forgot to delete already unnecessary

2022-06-15 08:31 UTC, ViacheslavKechkin commented on src/App.jsx
> +      <>
Adjacent JSX elements must be wrapped in an enclosing tag, so i use Fragment

2022-06-15 10:47 UTC, ViacheslavKechkin commented on src/components/Product/style.scss
> +  height: 90%;
Because 10% is needed for the action buttons that are lower

2022-06-15 13:00 UTC, ViacheslavKechkin commented on src/components/Search/index.jsx
> +            Общая стоимость выбранных блюд: {sum} р.
fixed it))

2022-06-16 07:35 UTC, d-vorobyov requested changes

2022-06-16 09:19 UTC, ViacheslavKechkin commented on src/App.jsx
> +  handleDeleteProduct = (isWindowDialog, productDelete) => {
If I remove the arrow function, then I need to do this  `this.handleDeleteProduct = this.handleDeleteProduct.bind(this)`. Is that what you mean?

2022-06-16 11:06 UTC, ViacheslavKechkin commented on src/App.jsx
> +          onHandleSearchChange={this.handleSearchChange}
Thank you very much)

2022-06-16 14:11 UTC, d-vorobyov commented on src/App.jsx
> +  handleDeleteProduct = (isWindowDialog, productDelete) => {
Yep, right, just checking your understand this)

2022-06-17 09:19 UTC, d-vorobyov requested changes

2022-06-17 09:19 UTC, d-vorobyov commented on src/App.jsx
> +            searchString: "",
Ok, look, I'm not sick perfectionist, it's just DRY principle)) It requires to use any part of information just once.
Let's look at your code:
```
this.setState(
      event.target.value || ""
        ? { searchString: event.target.value }
        : { searchString: "" }
)
```
Let's find common things and differences. Common - both objects have the same key `searchString`. Difference - their values. So we should use our ternary condition **just for differences**. Yeah, duplicates of `searchString` should make your eyes bleeding, train this feeling))
Second thing, as I said above, your possible values are `event.target.value` and `""`, there is no need for ternary actually. `||` operator returns right-hand value if left-hand is any falsish, so `this.setState({ searchString: event.target.value || "" })` is enough. Aaaand it also could be redundant since text input value is empty string if there is no text.

2022-06-17 09:19 UTC, d-vorobyov commented on src/App.jsx
> +          onDeletedWindow={this.handleDeletedWindow}
on Deleted (I guess just `Delete`) Window what? Open? Close?

2022-06-17 09:19 UTC, d-vorobyov commented on src/components/Product/index.jsx
> +    const { onDeletedWindow, onAddProduct, onChangeQuantity, el } = this.props;
Let's name `el` any other way, as I explained above

2022-06-17 09:19 UTC, d-vorobyov commented on src/components/Products/index.jsx
> +                el={el}
For example, here `product={product}` will be more clear to understand

2022-06-17 09:19 UTC, d-vorobyov commented on src/components/Products/index.jsx
> +            const { id } = el;
Not really need to destruct it here, but it you want to you can destruct with spread like:
```
({ id, ...restProduct }) => ... <Product key={`product-${id}`} product={{ id, ...restProduct }} ... />
```

2022-06-21 13:12 UTC, d-vorobyov requested changes

2022-06-22 13:51 UTC, d-vorobyov requested changes

2022-06-22 13:51 UTC, d-vorobyov commented on src/primitive/Button/index.jsx
> +        className="product__button"
Don't forget to set default `type`, usually `button`
If you will use this button inside form, a click may mistakenly trigger a form confirmation even if you not set `type="submit"`

2022-06-22 13:51 UTC, d-vorobyov commented on src/utils/index.jsx
> +  return toast.error(message, {
Remove function body, since there is just return

2022-06-23 08:43 UTC, d-vorobyov requested changes

2022-06-23 08:43 UTC, d-vorobyov commented on src/components/Product/index.jsx
> +            onChangeQuantity={() => onChangeQuantity({ product, add: true })}
name it more usual name to make it universal - `onClick`

2022-06-23 08:43 UTC, d-vorobyov commented on src/components/Product/index.jsx
> +            onChangeQuantity={() => onChangeQuantity({ product, add: false })}
name it more usual name to make it universal - `onClick`

2022-06-23 08:43 UTC, d-vorobyov commented on src/primitive/Button/index.jsx
> +    const { onChangeQuantity, ...restProps } = this.props;
onClick

2022-06-23 08:43 UTC, d-vorobyov commented on src/primitive/Button/index.jsx
>          {...restProps}
`restProps` _usually_ _(not always)_ should be spread after other props, another way in example if we want set other `type` - we won't cuz underlying `type="button"` overrides passed props

2022-06-23 09:07 UTC, merged